

-- SECTION 1 : PLATFORM OVERVIEW

-- OBJECTIVE: Understand overall marketplace size and revenue distribution

-- ===========================================================================================================================================

-- Problem 1: From which customer states do the highest number of orders come?
----------------------------------------------------------------------------------------------------------------------------------------------
USE Olist_Ecommerce;
SELECT 
    cu.customer_state,
    count(o.order_id) AS total_orders
FROM olist_customers_dataset cu
JOIN olist_orders_dataset o
    ON cu.customer_id = o.customer_id
WHERE
    order_status = 'delivered'
GROUP BY 
    cu.customer_state
ORDER BY 
    total_orders DESC;

-- Insight:
-- State SP has the highest order volume, indicating strong demand concentration.

-- ===========================================================================================================================================

-- Problem 2: What is the total revenue generated by each state?
----------------------------------------------------------------------------------------------------------------------------------------------
SELECT 
    cu.customer_state,
    COUNT(DISTINCT o.order_id) AS total_orders,
    ROUND(SUM(oi.price + oi.freight_value),2) AS total_revenue
FROM olist_customers_dataset cu
JOIN olist_orders_dataset o
    ON cu.customer_id = o.customer_id
JOIN olist_order_items_dataset oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY
    cu.customer_state
ORDER BY
    total_revenue DESC;

-- Insight:
-- SP generates the highest revenue by a large margin.
-- showing strong demand concentration in this state.

-- ===========================================================================================================================================

-- Problem 3: Which product categories generate the highest total reveue?
----------------------------------------------------------------------------------------------------------------------------------------------
SELECT 
    cn.product_category_name_english,
    ROUND(SUM(oi.price),2) AS total_revenue
FROM olist_order_items_dataset oi
JOIN olist_products_dataset pr
    ON oi.product_id = pr.product_id
JOIN product_category_name_translation cn
    ON pr.product_category_name = cn.product_category_name
WHERE pr.product_category_name IS NOT NULL
GROUP BY 
    cn.product_category_name_english
ORDER BY 
    total_revenue DESC;

-- Insight:
-- Health & beauty generates the highest total revenue.
-- indicating strong customer demand in this category.

-- ===========================================================================================================================================

-- Problem 4: Which product categories are most popular based on number of items sold?
----------------------------------------------------------------------------------------------------------------------------------------------
SELECT 
    pc.product_category_name_english AS category,
    COUNT(*) AS total_item_sold
FROM product_category_name_translation pc
JOIN olist_products_dataset pr
    ON pc.product_category_name = pr.product_category_name
JOIN olist_order_items_dataset oi
    ON pr.product_id = oi.product_id
JOIN olist_orders_dataset o
    ON oi.order_id = o.order_id
WHERE   
    o.order_status = 'delivered' -- AND
   -- pr.product_category_name IS NOT NULL
GROUP BY 
    PC.product_category_name_english
ORDER BY 
    total_item_sold DESC;

-- Insight:
-- Bed, bath & table is the most frequently purchased category.
-- showing high volume demand across customers.

-- ===========================================================================================================================================

-- Problem 5: Which month generated the highest total revenue?
----------------------------------------------------------------------------------------------------------------------------------------------
SELECT 
    TOP 1
    YEAR(o.order_purchase_timestamp) AS year ,
    MONTH(o.order_purchase_timestamp) AS month, 
    ROUND(SUM(oi.price + oi.freight_value),2) AS revenue
FROM olist_orders_dataset o
JOIN olist_order_items_dataset oi
    ON o.order_id = oi.order_id
WHERE 
    o.order_status = 'delivered'
GROUP BY 
    YEAR(o.order_purchase_timestamp),
    MONTH(o.order_purchase_timestamp)

ORDER BY revenue desc;

-- Insight:
-- November 2017 generated the highest monthly revenue.
-- indicating strong seasonal demand during this period.

-- ===========================================================================================================================================

-- Problem 6: Which state generated the highest total revenue?
----------------------------------------------------------------------------------------------------------------------------------------------
SELECT TOP 1
    cu.customer_state,
    ROUND(SUM(oi.price + oi.freight_value),2) AS total_revenue
FROM olist_customers_dataset cu
JOIN olist_orders_dataset o
    ON cu.customer_id = o.customer_id
JOIN olist_order_items_dataset oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY
    cu.customer_state
ORDER BY
    total_revenue DESC;

-- Insight:
-- SP generates the highest total revenue on the platform.
-- highlighting it as the strongest revenue-driving region.

-- ===========================================================================================================================================

-- Problem 7: How does revenue change month by month over time?
----------------------------------------------------------------------------------------------------------------------------------------------
SELECT
    FORMAT(o.order_purchase_timestamp, 'yyyy-MM') AS year_month,
    ROUND(SUM(oi.price + oi.freight_value),2) AS total_revenue
FROM olist_orders_dataset o
JOIN olist_order_items_dataset oi
    ON o.order_id = oi.order_id
WHERE 
    o.order_status = 'delivered'
GROUP BY
    FORMAT(o.order_purchase_timestamp, 'yyyy-MM')
ORDER BY
    year_month;

-- Insight:
-- Revenue shows steady growth throughout 2017.
-- with a clear peak in November, indicating strong seasonal demand.

-- ===========================================================================================================================================
-- ===========================================================================================================================================

-- SECTION 1 - PLATFORM OVERVIEW (FINAL INSIGHT)
----------------------------------------------------------------------------------------------------------------------------------------------
-- The marketplace shows strong revenue concentration in SP,
-- making it the dominant state in both orders and revenue.
-- Health & Beauty and Bed Bath & Table lead category performance,
-- indicating high consumer demand in lifestyle segments.
-- Revenue trends reveal consistent growth during 2017,
-- with a significant seasonal spike in November.
-- Overall, the platform demonstrates regional concentration
-- and strong year-over-year revenue expansion.
