

-- SECTION 2 : CUSTOMER BEHAVIOUR

-- OBJECTIVE: Understand customer loyalty and purchasing patterns.

-- ===========================================================================================================================================

-- Problem 1: Which customers are the most valuable based on total money spent?
----------------------------------------------------------------------------------------------------------------------------------------------
USE Olist_Ecommerce;
SELECT 
    cu.customer_unique_id,
    ROUND(SUM(oi.price + oi.freight_value),2) AS total_money_spent
FROM olist_customers_dataset cu
JOIN olist_orders_dataset o
    ON cu.customer_id = o.customer_id
JOIN olist_order_items_dataset oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY 
    cu.customer_unique_id
ORDER BY 
    total_money_spent DESC;

-- Insight:
-- A small group of customers contributes significantly higher total spending.
-- indicating the presence of high-value customers driving revenue concentration

-- ===========================================================================================================================================

-- Problem 2: Which customers are one-time buyers and which are repeat customers?
----------------------------------------------------------------------------------------------------------------------------------------------
SELECT 
    cu.customer_unique_id,
    COUNT(DISTINCT o.order_id) AS total_orders,
        CASE WHEN COUNT(DISTINCT o.order_id) = 1 THEN 'One-time buyer' 
            ELSE 'Repeat customer'
        END AS customer_type
FROM olist_customers_dataset cu
JOIN olist_orders_dataset o
    ON cu.customer_id = o.customer_id
GROUP BY 
    cu.customer_unique_id
ORDER BY 
    total_orders DESC;

-- Insight:
-- This separates one-time buyers from repeat customers.
-- based on their total number of orders.
-- One-time vs Repeat Customers (Correct Logic)

-- ===========================================================================================================================================

-- Problem 3: What percentage of customers are repeat customers?
----------------------------------------------------------------------------------------------------------------------------------------------
 SELECT 
    ( 100.0 * SUM(
        CASE WHEN total_orders > 1 THEN 1
        ELSE 0 END)/COUNT(*)) AS repeat_customer_percentage
FROM (
    SELECT
        cu.customer_unique_id,
        COUNT(DISTINCT o.order_id) AS
total_orders
    FROM
        olist_customers_dataset cu
    JOIN olist_orders_dataset o
        ON cu.customer_id = o.customer_id
GROUP BY 
    cu.customer_unique_id
    ) t;

-- Insight:
-- Only around 3% of customers return to make another purchase.
-- this indicates very low customer retention with most customers buying only once.

-- ===========================================================================================================================================

-- Problem 4: Among repeat customers only what is the average number of orders per customers?
----------------------------------------------------------------------------------------------------------------------------------------------
 SELECT 
    AVG(total_orders) AS avg_order_repeat_customers
    
FROM (
    SELECT
        cu.customer_unique_id,
        COUNT(DISTINCT o.order_id) AS
total_orders
    FROM
        olist_customers_dataset cu
    JOIN olist_orders_dataset o
        ON cu.customer_id = o.customer_id
GROUP BY 
    cu.customer_unique_id
HAVING
    COUNT(DISTINCT o.order_id) > 1
    ) t;

-- Insight:
-- Repeat customers place on average 2 orders each.
-- this shows that even returning customers are not highly frequent buyers.

-- ===========================================================================================================================================

-- Problem 5: what is the average revenue generated by repeat customers?
----------------------------------------------------------------------------------------------------------------------------------------------
SELECT 
    ROUND(AVG(total_revenue),2) AS avg_evenue_repeat_customer
FROM (
SELECT
    cu.customer_unique_id,
    SUM(oi.price + oi.freight_value) AS total_revenue,
    COUNT(DISTINCT o.order_id) AS total_orders
    FROM olist_customers_dataset cu
    JOIN olist_orders_dataset o
        ON cu.customer_id = o.customer_id
    JOIN olist_order_items_dataset oi
        ON o.order_id = oi.order_id
    GROUP BY 
        cu.customer_unique_id
    HAVING
        COUNT(DISTINCT o.order_id) > 1
        ) t;

-- Insight:
-- On average, repeat customers generate around 310 in total revenue.
-- this shows that returning customers contribute meaningful value per user.

-- ===========================================================================================================================================

-- Problem 6: what is the average revenue generated by one-time customers?
----------------------------------------------------------------------------------------------------------------------------------------------
SELECT 
    ROUND(AVG(total_revenue),2) AS avg_Revenue_one_time_customer
FROM (
SELECT
    cu.customer_unique_id,
    SUM(oi.price + oi.freight_value) AS total_revenue,
    COUNT(DISTINCT o.order_id) AS total_orders
    FROM olist_customers_dataset cu
    JOIN olist_orders_dataset o
        ON cu.customer_id = o.customer_id
    JOIN olist_order_items_dataset oi
        ON o.order_id = oi.order_id
    GROUP BY 
        cu.customer_unique_id
    HAVING
        COUNT(DISTINCT o.order_id) = 1
        ) t;

-- Insight:
-- One-time customers generate an average revenue of 161 which is significally lower than repeat customers.

-- ===========================================================================================================================================

-- Problem 7: Rank customers by total lifetime revenue?
----------------------------------------------------------------------------------------------------------------------------------------------
WITH customer_revenue AS (
    SELECT
        cu.customer_unique_id,
        ROUND(SUM(oi.price + oi.freight_value),2) AS lifetime_revenue
    FROM olist_customers_dataset cu
    JOIN olist_orders_dataset o
        ON cu.customer_id = o.customer_id
    JOIN olist_order_items_dataset oi
        ON o.order_id = oi.order_id
    WHERE o.order_status = 'delivered'
    GROUP BY cu.customer_unique_id
)
SELECT *,
       DENSE_RANK() OVER (ORDER BY lifetime_revenue DESC) AS revenue_rank
FROM customer_revenue
ORDER BY revenue_rank;

-- Insight:
-- A small group of customers contributes very high lifetime revenue.
-- indicating strong revenue concentration among top buyers.

-- ===========================================================================================================================================

-- Problem 8: For each customer, find their first and last order date
----------------------------------------------------------------------------------------------------------------------------------------------
SELECT 
    cu.customer_unique_id,
    Min(o.order_purchase_timestamp) AS old,
    MAX(o.order_purchase_timestamp) AS latest
FROM olist_customers_dataset cu
JOIN olist_orders_dataset o
    ON cu.customer_id = o.customer_id
WHERE
    o.order_status = 'delivered'
GROUP BY 
    cu.customer_unique_id 
ORDER BY
    cu.customer_unique_id;

-- Insight:
-- Many customers have the same first and last order date,
-- indicating a large portion of one-time buyers on the platform.

-- ===========================================================================================================================================

-- Problem 9: For each customer, find the gap (in days) between their consecutive delivered orders.
----------------------------------------------------------------------------------------------------------------------------------------------
WITH ordered_deliveries AS (
    SELECT
        cu.customer_unique_id,
        o.order_delivered_customer_date AS current_delivered_date,
        LAG(o.order_delivered_customer_date) OVER (
            PARTITION BY cu.customer_unique_id
            ORDER BY o.order_delivered_customer_date
        ) AS previous_delivered_date
    FROM olist_customers_dataset cu
    JOIN olist_orders_dataset o
        ON cu.customer_id = o.customer_id
    WHERE
        o.order_status = 'delivered'
        AND o.order_delivered_customer_date IS NOT NULL   
)

SELECT
    customer_unique_id,
    previous_delivered_date,
    current_delivered_date,
    DATEDIFF(DAY, previous_delivered_date, current_delivered_date) AS gap_days
FROM ordered_deliveries
WHERE
    previous_delivered_date IS NOT NULL
ORDER BY 
    gap_days DESC,
    customer_unique_id,
    current_delivered_date;

-- Insight:
-- The gap between consecutive purchases is often very large (500+ days for many customers)
-- indicating weak repeat frequency and low purchasing momentum.

-- ===========================================================================================================================================

-- Problem 10: Which customers have the longest customer lifetime on the platform?
----------------------------------------------------------------------------------------------------------------------------------------------
WITH customer_lifetime AS (
    SELECT
        cu.customer_unique_id,
        MIN(o.order_delivered_customer_date) AS first_delivered_date,
        MAX(o.order_delivered_customer_date) AS last_delivered_date,
        DATEDIFF(
            DAY,
            MIN(o.order_delivered_customer_date),
            MAX(o.order_delivered_customer_date)
        ) AS lifetime_days
    FROM olist_customers_dataset cu
    JOIN olist_orders_dataset o
        ON cu.customer_id = o.customer_id
    WHERE
        o.order_status = 'delivered'
        AND o.order_delivered_customer_date IS NOT NULL
    GROUP BY
        cu.customer_unique_id
)

SELECT
    customer_unique_id,
    first_delivered_date,
    last_delivered_date,
    lifetime_days
FROM customer_lifetime
ORDER BY lifetime_days DESC;

-- Insight:
-- A small group of customers stay active on the platform for more than 1.5 years,
-- indicating the presence of long-term loyal customers.

-- ===========================================================================================================================================

-- Problem 11: How many customers ordered 1 time, 2 times, 3 times, 4+ times?
----------------------------------------------------------------------------------------------------------------------------------------------
WITH customer_orders AS (
    SELECT
        cu.customer_unique_id,
        COUNT(DISTINCT o.order_id) AS total_orders
    FROM olist_orders_dataset o
    JOIN olist_customers_dataset cu
        ON o.customer_id = cu.customer_id
    WHERE o.order_status = 'delivered'
    GROUP BY cu.customer_unique_id
),
buckets AS (
    SELECT
        CASE
            WHEN total_orders = 1 THEN '1 Order'
            WHEN total_orders = 2 THEN '2 Orders'
            WHEN total_orders = 3 THEN '3 Orders'
            ELSE '4+ Orders'
        END AS order_frequency_group,
        CASE
            WHEN total_orders = 1 THEN 1
            WHEN total_orders = 2 THEN 2
            WHEN total_orders = 3 THEN 3
            ELSE 4
        END AS sort_key,
        COUNT(*) AS number_of_customers
    FROM customer_orders
    GROUP BY
        CASE
            WHEN total_orders = 1 THEN '1 Order'
            WHEN total_orders = 2 THEN '2 Orders'
            WHEN total_orders = 3 THEN '3 Orders'
            ELSE '4+ Orders'
        END,
        CASE
            WHEN total_orders = 1 THEN 1
            WHEN total_orders = 2 THEN 2
            WHEN total_orders = 3 THEN 3
            ELSE 4
        END
)

SELECT
    order_frequency_group,
    number_of_customers,
    CAST(
        number_of_customers * 100.0
        / SUM(number_of_customers) OVER ()
        AS DECIMAL(5,2)
    ) AS percentage
FROM buckets
ORDER BY sort_key;

-- Insight:
-- Around 97% of customers purchase only once,
-- showing very low repeat buying behavior on the platform.

-- ===========================================================================================================================================
-- ===========================================================================================================================================

-- SECTION 2 - CUSTOMER BEHAVIOR ANALYSIS (FINAL INSIGHT)
----------------------------------------------------------------------------------------------------------------------------------------------
-- The platform is largely driven by one-time buyers, 
-- with nearly 97% of customers purchasing only once.
-- Although repeat customers represent a very small share, 
-- they generate nearly double the average revenue per customer (~₹310 vs ₹161). 
-- Long purchase gaps (often 500+ days) indicate weak retention and low repeat momentum.
